version: "3.7"

services:
  mysqld-exporter:
    container_name: mysqld-exporter
    image: prom/mysqld-exporter:v0.12.1
    ports:
      - 9104:9104
    network_mode: host
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      DATA_SOURCE_NAME: exporter:password@(localhost:13306)/
    deploy:
      resources:
        limits:
          memory: 20m
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  mysql-exporter:
    image: mysql:8.0.23
    container_name: mysql-exporter
    ports:
      - 13306:3306
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      - MYSQL_DATABASE=exporter
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - TZ=UTC
    volumes:
      - ./mysql/datadir:/var/lib/mysql:rw
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d:ro
    restart: always

  prometheus:
    container_name: prometheus-exporter
    image: prom/prometheus:v2.24.1
    volumes:
      - ./prometheus/etc/prometheus/:/etc/prometheus/:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    network_mode: host
    restart: always

  grafana:
    container_name: grafana-exporter
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    network_mode: host
    restart: always